version: '3.8'
services:
  webserver:
    container_name: movie-listing-webserver
    image: 'nginx:alpine'
    depends_on:
      - app
    ports:
      - "8005:80"
    networks:
      - movie-listing-network
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'

  app:
    container_name: movie-listing-app
#    build:
#      context: .
#      dockerfile: docker/php-fpm/Dockerfile
#      target: development
    image: php:8.2-fpm-alpine
    volumes:
      - './:/var/www'
    working_dir: /var/www
    networks:
      - movie-listing-network

networks:
  movie-listing-network: