version: '3'
services:
  dev:
    container_name: movie_listing-dev
    ports:
      - "4361:443"
      - "861:80"
    image: localhost:5000/movie_listing
    volumes:
      - /home/guille/dockers/movie_listing/volumes/dev:/var/www/html
networks:
  default:
    name: dockers_guille
    external: true